Improve accessibility
Ableton/ableton.github.io pull request #19
Opened 2024-03-08 08:05 UTC by WebSnke

2024-03-22 14:28 UTC, lzh-ableton requested changes
Hi @WebSnke. Thank you for your PR! 

I have a few suggestions to improve the `lang` attribute implementation. I'll explain them here and then leave comments on each file to change.

1. Instead of `en-US`, we can use `en`. This is because in general, shorter language tags are preferred. (See [W3: Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/#overview): _The golden rule when creating language tags is to keep the tag as short as possible. Avoid region, script or other subtags except where they add useful distinguishing information._)

2. Since our site is only in English, we can set the `lang` attribute directly in the `html` tag of layout files (which looks like was your original approach). This avoids the overhead of adding the property individually to all .md files, an approach which would be more useful if we had multiple languages to support.

Other than those changes, before we can merge your PR, we need a signed CLA. You can find all the information on https://ableton.github.io/cla/

Thanks and let me know if you have any questions!

2024-03-22 14:28 UTC, lzh-ableton commented on _layouts/default.html
Please add `lang="en"` to the `html` tag.

2024-03-22 14:28 UTC, lzh-ableton commented on _layouts/link.html
Please add `lang="en"` to the `html` tag.

2024-03-22 14:28 UTC, lzh-ableton commented on _layouts/linkkit.html
Please add `lang="en"` to the `html` tag.

2024-03-22 14:28 UTC, lzh-ableton commented on export/index.md
> +lang: en-US
Please remove this line.

2024-03-22 14:28 UTC, lzh-ableton commented on index.md
> +lang: en-US
Please remove this line.

2024-03-22 14:28 UTC, lzh-ableton commented on link/index.md
> +lang: en-US
Please remove this line.

2024-03-22 14:28 UTC, lzh-ableton commented on linkkit/index.md
> +lang: en-US
Please remove this line.

2024-03-22 17:27 UTC, WebSnke commented
> Hi @WebSnke. Thank you for your PR!
> 
> I have a few suggestions to improve the `lang` attribute implementation. I'll explain them here and then leave comments on each file to change.
> 
>     1. Instead of `en-US`, we can use `en`. This is because in general, shorter language tags are preferred. (See [W3: Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/#overview): _The golden rule when creating language tags is to keep the tag as short as possible. Avoid region, script or other subtags except where they add useful distinguishing information._)
> 
>     2. Since our site is only in English, we can set the `lang` attribute directly in the `html` tag of layout files (which looks like was your original approach). This avoids the overhead of adding the property individually to all .md files, an approach which would be more useful if we had multiple languages to support.
> 
> 
> Other than those changes, before we can merge your PR, we need a signed CLA. You can find all the information on https://ableton.github.io/cla/
> 
> Thanks and let me know if you have any questions!

1. I used the en-us because specififying the dialect is helpful for screen readers.
2. Sure, I can revert the changes.

2024-03-22 17:28 UTC, psjnek commented
I also signed the CLA already.

2024-03-28 16:57 UTC, lzh-ableton commented
> 1. I used the en-us because specififying the accent is helpful for screen readers.

In our case, our content being spoken in a US dialect isn't a necessity, and regardless, region subtags are typically ignored (source: [WebAIM: Document and Content Language](https://webaim.org/techniques/language/#region)). We also use `en` on ableton.com, rather than `en-US`. If you could change this then the PR would be good to go!

> I also signed the CLA already.

Great, thanks!

2024-04-03 14:59 UTC, lzh-ableton approved these changes
LGTM! Thank you for your contribution @WebSnke!

@nre-ableton This could be merged when you have the chance.

2024-04-03 15:12 UTC, nre-ableton commented
I took the liberty of rebasing your branch to drop the "Move language attribute to Markdown files" commit and its corresponding revert.

2024-04-03 15:13 UTC, nre-ableton approved these changes

2024-04-03 15:13 UTC, merged

2024-04-03 19:03 UTC, WebSnke commented
Thanks. May I ask how you got your job at Ableton as a developer btw?

2024-04-04 07:06 UTC, nre-ableton commented
> Thanks. May I ask how you got your job at Ableton as a developer btw?

Keep your eye on https://www.ableton.com/jobs 🙂